# Generated by Django 3.2.4 on 2021-07-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorantapp', '0002_weapons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
