# Generated by Django 3.2.4 on 2021-07-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorantapp', '0003_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='author',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characters',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapons',
            name='author',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapons',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characters',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
