# Generated by Django 3.2.4 on 2021-07-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valorantapp', '0004_auto_20210719_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='author',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weapons',
            name='author',
        ),
        migrations.RemoveField(
            model_name='weapons',
            name='date',
        ),
    ]
